// Shared real-name scrubber for SFC Take content.
//
// The SFC Take is candidate-facing text generated by Claude and then
// rendered to recruiters who have NOT yet been approved for an
// introduction. Recruiters at that stage must not see the candidate's
// real name. The take is supposed to use the anonymized handle
// (display_name) but the model occasionally regurgitates the real
// name from the prompt context.
//
// This module is the single source of truth for replacing real-name
// occurrences with the anonymized display_name. It's applied:
//   1. In api/generate-sfc-take.ts immediately before writing to the
//      DB, so newly-generated takes never store the real name.
//   2. In api/publish-sfc-take.ts immediately before flipping
//      sfc_take_published_at, so any admin-edited draft (the manual
//      SfcTakeEditor save goes direct to Supabase from the browser and
//      is therefore unscrubbed at write time) gets cleaned on publish.
//   3. By api/backfill-sfc-take-scrub.js as a one-shot to clean any
//      legacy rows that were written before this scrubber existed.
//
// The historical client-side scrub in src/pages/CandidateSearch.tsx
// (which required shipping `name` to recruiter browsers — exactly the
// leak this whole change closes) has been removed.

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Replace word-bounded occurrences of `realName` (and its first-name
// component) in `text` with `anonName`. Word boundaries prevent
// false positives like turning "estimate" into "esanonName" when the
// first name happens to be "Tim".
function scrubName(text, realName, anonName) {
  if (!text || typeof text !== 'string') return text;
  if (!realName || typeof realName !== 'string') return text;
  const anon = anonName || 'this candidate';
  let out = text;

  const real = realName.trim();
  if (real && real !== anon) {
    // Full name first (longest match).
    out = out.replace(new RegExp(`\\b${escapeRegex(real)}\\b`, 'g'), anon);
    // Then the first-name component, if distinct.
    const first = real.split(/\s+/)[0];
    if (first && first !== anon && first.length >= 2) {
      out = out.replace(new RegExp(`\\b${escapeRegex(first)}\\b`, 'g'), anon);
    }
  }
  return out;
}

// Convenience: scrub every element of a text[] (sfc_role_fit,
// sfc_strengths, sfc_considerations). Non-strings pass through.
function scrubNameInArray(arr, realName, anonName) {
  if (!Array.isArray(arr)) return arr;
  return arr.map(item => (typeof item === 'string' ? scrubName(item, realName, anonName) : item));
}

// Scrub every SFC Take column in one pass. Returns a new object with
// the four scrubbed fields — call sites spread this into their DB
// update payload so the persisted row is clean.
function scrubSfcTakeFields({ sfc_take, sfc_role_fit, sfc_strengths, sfc_considerations }, realName, anonName) {
  return {
    sfc_take: scrubName(sfc_take, realName, anonName),
    sfc_role_fit: scrubNameInArray(sfc_role_fit, realName, anonName),
    sfc_strengths: scrubNameInArray(sfc_strengths, realName, anonName),
    sfc_considerations: scrubNameInArray(sfc_considerations, realName, anonName),
  };
}

export { scrubName, scrubNameInArray, scrubSfcTakeFields };
