// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drkdfigzhdkujlbxeqmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRya2RmaWd6aGRrdWpsYnhlcW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDE4NTAsImV4cCI6MjA2ODExNzg1MH0.UIykZolmLBORgJ_PF-DEIRU-VG7ZA3ecdveGh0wy4aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});