// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxvohpriumqvjjcsfjvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dm9ocHJpdW1xdmpqY3NmanZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDAxNDEsImV4cCI6MjA2ODExNjE0MX0.qBAEmYsp7q7dZcUVc_fXBuSfsfgu1baEPl4D_mICZ_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});